In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [41]:
data = pd.read_csv('shooting-1982-2023.csv')
data.head(15)

,case,location,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,prior_signs_mental_health_issues,...,weapons_obtained_legally,where_obtained,weapon_type,weapon_details,race,gender,latitude,longitude,type,year
0,Nashville religious school shooting,"Nashville,Tennessee",3/27/2023,"Audrey Hale, 28, who was a former student at t...",6,1,6,School,28,-,...,-,-,"semiautomatic rifle, semiautomatic handgun",-,-,"F (identified as transgender, per police)",NaN,NaN,Mass,2023
1,Michigan State University shooting,"East Lansing, Michigan",2/13/2023,"Anthony D. McRae, 43, opened fire at Berkey Ha...",3,5,8,School,43,-,...,yes,-,semiautomatic handguns,-,Black,M,NaN,NaN,Mass,2023
2,Half Moon Bay spree shooting,"Half Moon Bay, California",1/23/2023,"Chunli Zhao, 67, suspected of carrying out the...",7,1,8,workplace,67,-,...,-,-,semiautomatic handgun,-,Asian,M,NaN,NaN,Spree,2023
3,LA dance studio mass shooting,"Monterey Park, California",1/21/2023,"Huu Can Tran, 72,Â fled the scene in a white va...",11,10,21,Other,72,yes,...,-,-,semiautomatic assault weapon (Details pending),-,Asian,M,NaN,NaN,Mass,2023
4,Virginia Walmart shooting,"Chesapeake, Virginia",11/22/2022,"Andre Bing, 31, who worked as a supervisor at ...",6,6,12,Workplace,31,-,...,-,-,semiautomatic handgun,-,Black,M,NaN,NaN,Mass,2022
5,LGBTQ club shooting,"Colorado Springs, Colorado",11/19/2022,"Anderson L. Aldrich, 22, wore body armor and o...",5,25,30,Other,22,yes,...,-,-,semiautomatic rifle; semiautomatic handgun,-,White,M,NaN,NaN,Mass,2022
6,University of Virginia shooting,"Charlottesville, Virginia",11/13/2022,"Christopher Darnell Jones Jr., 22, allegedly o...",3,2,5,School,22,-,...,yes,"Dance's Sporting Goods; Colonial Heights, VA",semiautomatic pistol,Glock 45 9mm; Ruger AR-556 rifle (in his dorm ...,Black,M,NaN,NaN,Mass,2022
7,Raleigh spree shooting,"Hedingham, North Carolina",10/13/2022,"Austin Thompson, 15, went on a rampage in the ...",5,2,7,Other,15,-,...,-,-,"shotgun, semiautomatic handgun",NaN,White,M,NaN,NaN,Spree,2022
8,Greenwood Park Mall shooting,"Greenwood, Indiana",7/17/2022,"Jonathan Sapirman, 20, opened fire in a mall f...",3,2,5,workplace,20,-,...,yes,in Greenwood,semiautomatic rifles; semiautomatic handgun,Sig Sauer M400 rifle,White,M,NaN,NaN,Mass,2022
9,Highland Park July 4 parade shooting,"Highland Park, Illinois",7/4/2022,"Suspected gunman Robert ""Bobby"" Crimo, 21, all...",7,46,53,Other,21,-,...,yes,"legally purchased by the shooter in the ""great...",semiautomatic rifle,"AR-15 style rifle, possibly modified for rapid...",White,M,NaN,NaN,Mass,2022
10,Church potluck dinner shooting,"Birmingham, Alabama",6/16/2022,"Robert Findlay Smith, 70, opened fire with a h...",3,0,3,religious,70,-,...,yes,-,semiautomatic handgun,-,White,M,NaN,NaN,Mass,2022
11,Concrete company shooting,"Smithsburg, Maryland",6/9/2022,"Joe Louis Esquivel, 23, shot four coworkers an...",3,1,4,workplace,23,-,...,-,-,semiautomatic handgun,-,-,M,NaN,NaN,Mass,2022
12,Tulsa medical center shooting,"Tulsa, Oklahoma",6/1/2022,"Michael Louis, 45, killed four, including two ...",4,9,13,workplace,45,-,...,yes,-,semiautomatic rifle; semiautomatic handgun,AR-15 style rifle,Black,M,NaN,NaN,Mass,2022
13,Robb Elementary School massacre,"Uvalde, Texas",5/24/2022,"Salvador Ramos, 18, was identified by authorit...",21,17,38,School,18,yes,...,yes,-,semiautomatic rifles,-,Latino,M,NaN,NaN,Mass,2022
14,Buffalo supermarket massacre,"Buffalo, New York",5/14/2022,"Payton S. Gendron, 18, committed a racially mo...",10,3,13,workplace,18,yes,...,yes,-,semiautomatic rifle,Bushmaster XM-15 semiautomatic rifle,White,M,NaN,NaN,Mass,2022

In [42]:
data.columns

Index(['case', 'location', 'date', 'summary', 'fatalities', 'injured',
       'total_victims', 'location.1', 'age_of_shooter',
       'prior_signs_mental_health_issues', 'mental_health_details',
       'weapons_obtained_legally', 'where_obtained', 'weapon_type',
       'weapon_details', 'race', 'gender', 'latitude', 'longitude', 'type',
       'year'],
      dtype='object')

In [43]:
data['location.1'].value_counts()

Other          50
Workplace      45
School         22
Religious       7
Military        6
workplace       5
Other\n         3
\nWorkplace     1
religious       1
Airport         1
Name: location.1, dtype: int64

In [44]:
data.replace({'Other\n':'Other',
             'workplace':'Workplace',
              '\nWorkplace':'Workplace',
             'religious':'Religious',
             },inplace=True)

In [45]:
data['location.1'].value_counts()

Other        53
Workplace    51
School       22
Religious     8
Military      6
Airport       1
Name: location.1, dtype: int64

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 21 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   case                              141 non-null    object
 1   location                          141 non-null    object
 2   date                              141 non-null    object
 3   summary                           141 non-null    object
 4   fatalities                        141 non-null    int64
 5   injured                           141 non-null    int64
 6   total_victims                     141 non-null    int64
 7   location.1                        141 non-null    object
 8   age_of_shooter                    141 non-null    int64
 9   prior_signs_mental_health_issues  141 non-null    object
 10  mental_health_details             141 non-null    object
 11  weapons_obtained_legally          141 non-null    object
 12  where_obtained                    141 non-null    object
 13  weapon_type                       141 non-null    object
 14  weapon_details                    140 non-null    object
 15  race                              141 non-null    object
 16  gender                            141 non-null    object
 17  latitude                          126 non-null    float64
 18  longitude                         126 non-null    float64
 19  type                              141 non-null    object
 20  year                              141 non-null    int64
dtypes: float64(2), int64(5), object(14)
memory usage: 23.3+ KB

In [47]:
data['race'].value_counts()

white              41
White              31
Black              16
-                  13
Latino             11
Asian              10
black               9
Other               5
Native American     3
unclear             1
White               1
Name: race, dtype: int64

In [48]:
data.replace({'white':'White',
              'White':'White',
              'White ':'White',
             'black':'Black',
              '-':'unclear',
             'unclear':'Unclear'
             },inplace=True)

In [49]:
data['race'].value_counts()

White              73
Black              25
unclear            13
Latino             11
Asian              10
Other               5
Native American     3
Unclear             1
Name: race, dtype: int64

In [50]:
data['gender'].value_counts()

Male                                         70
M                                            65
Female                                        2
Male & Female                                 2
F                                             1
F (identified as transgender, per police)     1
Name: gender, dtype: int64

In [51]:
data.replace({'M':'Male',
              'F':'Female'
            
             },inplace=True)

In [52]:
data['gender'].value_counts()

Male                                         135
Female                                         3
Male & Female                                  2
F (identified as transgender, per police)      1
Name: gender, dtype: int64

In [53]:
data['prior_signs_mental_health_issues'].unique()

array(['unclear', 'yes', 'TBD', 'Yes', 'Unclear', 'Unknown', 'No',
       'Unclear '], dtype=object)

In [54]:
data.replace({'yes':'Yes',
              'unclear':'Unclear',
              'Unclear ':'Unclear',
            'TBD':'To Be  Determined'
             },inplace=True)

In [55]:
 data['prior_signs_mental_health_issues'].value_counts()

Yes                  66
Unclear              52
No                   17
To Be  Determined     5
Unknown               1
Name: prior_signs_mental_health_issues, dtype: int64

In [56]:
data['race'].unique()

array(['Unclear', 'Black', 'Asian', 'White', 'Latino', 'Other',
       'Native American'], dtype=object)

In [57]:
data[['City','State']]=data ['location'].str.split(',',expand = True)

In [58]:
data['State']=data['State'].str.lstrip()

In [59]:
data['State'].unique()

array(['Tennessee', 'Michigan', 'California', 'Virginia', 'Colorado',
       'North Carolina', 'Indiana', 'Illinois', 'Alabama', 'Maryland',
       'Oklahoma', 'Texas', 'New York', 'Georgia', 'Missouri',
       'Wisconsin', 'New Jersey', 'Florida', 'Ohio', 'Pennsylvania',
       'Nevada', 'Washington', 'Louisiana', 'Kansas', 'Oregon',
       'South Carolina', 'District of Columbia', 'Connecticut',
       'Minnesota', 'Arizona', 'Kentucky', 'Nebraska', 'Utah',
       'Mississippi', 'Massachusetts', 'Hawaii', 'Arkansas', 'Iowa'],
      dtype=object)

In [60]:
data

,case,location,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,prior_signs_mental_health_issues,...,weapon_type,weapon_details,race,gender,latitude,longitude,type,year,City,State
0,Nashville religious school shooting,"Nashville,Tennessee",3/27/2023,"Audrey Hale, 28, who was a former student at t...",6,1,6,School,28,Unclear,...,"semiautomatic rifle, semiautomatic handgun",Unclear,Unclear,"F (identified as transgender, per police)",NaN,NaN,Mass,2023,Nashville,Tennessee
1,Michigan State University shooting,"East Lansing, Michigan",2/13/2023,"Anthony D. McRae, 43, opened fire at Berkey Ha...",3,5,8,School,43,Unclear,...,semiautomatic handguns,Unclear,Black,Male,NaN,NaN,Mass,2023,East Lansing,Michigan
2,Half Moon Bay spree shooting,"Half Moon Bay, California",1/23/2023,"Chunli Zhao, 67, suspected of carrying out the...",7,1,8,Workplace,67,Unclear,...,semiautomatic handgun,Unclear,Asian,Male,NaN,NaN,Spree,2023,Half Moon Bay,California
3,LA dance studio mass shooting,"Monterey Park, California",1/21/2023,"Huu Can Tran, 72,Â fled the scene in a white va...",11,10,21,Other,72,Yes,...,semiautomatic assault weapon (Details pending),Unclear,Asian,Male,NaN,NaN,Mass,2023,Monterey Park,California
4,Virginia Walmart shooting,"Chesapeake, Virginia",11/22/2022,"Andre Bing, 31, who worked as a supervisor at ...",6,6,12,Workplace,31,Unclear,...,semiautomatic handgun,Unclear,Black,Male,NaN,NaN,Mass,2022,Chesapeake,Virginia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,Shopping centers spree killings,"Palm Bay, Florida",23-04-1987,"Retired librarian William Cruse, 59, was paran...",6,14,20,Other,59,Yes,...,"One rifle, one revolver, one shotgun","Sturm, Ruger Mini-14 semiautomatic rifle; 20-g...",White,Male,28.033189,-80.642969,Spree,1987,Palm Bay,Florida
137,United States Postal Service shooting,"Edmond, Oklahoma",20-08-1986,"Postal worker Patrick Sherrill, 44, opened fir...",15,6,21,Workplace,44,Unclear,...,Three semiautomatic handguns,".22-caliber, two .45-caliber Colt Model 1911-A...",White,Male,35.667202,-97.429370,Mass,1986,Edmond,Oklahoma
138,San Ysidro McDonald's massacre,"San Ysidro, California",18-07-1984,"James Oliver Huberty, 41, opened fire in a McD...",22,19,41,Other,41,Yes,...,"One semiautomatic handgun, one rifle (assault)...",9mm Browning P35 Hi-Power semiautomatic handgu...,White,Male,32.552001,-117.043081,Mass,1984,San Ysidro,California
139,Dallas nightclub shooting,"Dallas, Texas",29-06-1984,"Abdelkrim Belachheb, 39, opened fire at an ups...",6,1,7,Other,39,Yes,...,One semiautomatic handgun,9mm Smith & Wesson 459 semiautomatic handgun,White,Male,32.925166,-96.838676,Mass,1984,Dallas,Texas
140,Welding shop shooting,"Miami, Florida",20-08-1982,"Junior high school teacher Carl Robert Brown, ...",8,3,11,Other,51,Yes,...,One shotgun,Mossberg 500 Persuader pump-action shotgun wit...,White,Male,25.796491,-80.226683,Mass,1982,Miami,Florida

In [61]:
# Add state code and add to df
state_to_code = {'District of Columbia' : 'DC','Mississippi': 'MS', 'Oklahoma': 'OK', 'Delaware': 'DE', 
                 'Minnesota': 'MN', 'Illinois': 'IL', 'Arkansas': 'AR', 'New Mexico': 'NM', 'Indiana': 'IN', 
                 'Maryland': 'MD', 'Louisiana': 'LA', 'Idaho': 'ID', 'Wyoming': 'WY', 'Tennessee': 'TN', 
                 'Arizona': 'AZ', 'Iowa': 'IA', 'Michigan': 'MI', 'Kansas': 'KS', 'Utah': 'UT', 'Virginia': 
                 'VA', 'Oregon': 'OR', 'Connecticut': 'CT', 'Montana': 'MT', 'California': 'CA', 'Massachusetts': 'MA',
                 'West Virginia': 'WV', 'South Carolina': 'SC', 'New Hampshire': 'NH', 'Wisconsin': 'WI', 
                 'Vermont': 'VT', 'Georgia': 'GA', 'North Dakota': 'ND', 'Pennsylvania': 'PA', 'Florida': 'FL', 
                 'Alaska': 'AK', 'Kentucky': 'KY', 'Hawaii': 'HI', 'Nebraska': 'NE', 'Missouri': 'MO', 'Ohio': 'OH',
                 'Alabama': 'AL', 'Rhode Island': 'RI', 'South Dakota': 'SD', 'Colorado': 'CO', 'New Jersey': 'NJ',
                 'Washington': 'WA', 'North Carolina': 'NC', 'New York': 'NY', 'Texas': 'TX', 'Nevada': 'NV',
                 'Maine': 'ME', 'Puerto Rico': 'PR'}
data['State Code'] = data['State'].apply(lambda x : state_to_code[x])
data.head()

,case,location,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,prior_signs_mental_health_issues,...,weapon_details,race,gender,latitude,longitude,type,year,City,State,State Code
0,Nashville religious school shooting,"Nashville,Tennessee",3/27/2023,"Audrey Hale, 28, who was a former student at t...",6,1,6,School,28,Unclear,...,Unclear,Unclear,"F (identified as transgender, per police)",NaN,NaN,Mass,2023,Nashville,Tennessee,TN
1,Michigan State University shooting,"East Lansing, Michigan",2/13/2023,"Anthony D. McRae, 43, opened fire at Berkey Ha...",3,5,8,School,43,Unclear,...,Unclear,Black,Male,NaN,NaN,Mass,2023,East Lansing,Michigan,MI
2,Half Moon Bay spree shooting,"Half Moon Bay, California",1/23/2023,"Chunli Zhao, 67, suspected of carrying out the...",7,1,8,Workplace,67,Unclear,...,Unclear,Asian,Male,NaN,NaN,Spree,2023,Half Moon Bay,California,CA
3,LA dance studio mass shooting,"Monterey Park, California",1/21/2023,"Huu Can Tran, 72,Â fled the scene in a white va...",11,10,21,Other,72,Yes,...,Unclear,Asian,Male,NaN,NaN,Mass,2023,Monterey Park,California,CA
4,Virginia Walmart shooting,"Chesapeake, Virginia",11/22/2022,"Andre Bing, 31, who worked as a supervisor at ...",6,6,12,Workplace,31,Unclear,...,Unclear,Black,Male,NaN,NaN,Mass,2022,Chesapeake,Virginia,VA

In [62]:
data.columns

Index(['case', 'location', 'date', 'summary', 'fatalities', 'injured',
       'total_victims', 'location.1', 'age_of_shooter',
       'prior_signs_mental_health_issues', 'mental_health_details',
       'weapons_obtained_legally', 'where_obtained', 'weapon_type',
       'weapon_details', 'race', 'gender', 'latitude', 'longitude', 'type',
       'year', 'City', 'State', 'State Code'],
      dtype='object')

In [63]:
# Define age bins with a minimum age of 11 and maximum age of 72
age_bins = [11, 19, 35, 64, 72]

# Define labels for age bins
age_labels = ['10-18', '19-34', '35-64', '65-72']

data['age_group'] = pd.cut(data['age_of_shooter'], age_bins, labels=age_labels)

data.head()

,case,location,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,prior_signs_mental_health_issues,...,race,gender,latitude,longitude,type,year,City,State,State Code,age_group
0,Nashville religious school shooting,"Nashville,Tennessee",3/27/2023,"Audrey Hale, 28, who was a former student at t...",6,1,6,School,28,Unclear,...,Unclear,"F (identified as transgender, per police)",NaN,NaN,Mass,2023,Nashville,Tennessee,TN,19-34
1,Michigan State University shooting,"East Lansing, Michigan",2/13/2023,"Anthony D. McRae, 43, opened fire at Berkey Ha...",3,5,8,School,43,Unclear,...,Black,Male,NaN,NaN,Mass,2023,East Lansing,Michigan,MI,35-64
2,Half Moon Bay spree shooting,"Half Moon Bay, California",1/23/2023,"Chunli Zhao, 67, suspected of carrying out the...",7,1,8,Workplace,67,Unclear,...,Asian,Male,NaN,NaN,Spree,2023,Half Moon Bay,California,CA,65-72
3,LA dance studio mass shooting,"Monterey Park, California",1/21/2023,"Huu Can Tran, 72,Â fled the scene in a white va...",11,10,21,Other,72,Yes,...,Asian,Male,NaN,NaN,Mass,2023,Monterey Park,California,CA,65-72
4,Virginia Walmart shooting,"Chesapeake, Virginia",11/22/2022,"Andre Bing, 31, who worked as a supervisor at ...",6,6,12,Workplace,31,Unclear,...,Black,Male,NaN,NaN,Mass,2022,Chesapeake,Virginia,VA,19-34

In [64]:
data['age_of_shooter']= data['age_of_shooter'].astype(str)
data.head()

,case,location,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,prior_signs_mental_health_issues,...,race,gender,latitude,longitude,type,year,City,State,State Code,age_group
0,Nashville religious school shooting,"Nashville,Tennessee",3/27/2023,"Audrey Hale, 28, who was a former student at t...",6,1,6,School,28,Unclear,...,Unclear,"F (identified as transgender, per police)",NaN,NaN,Mass,2023,Nashville,Tennessee,TN,19-34
1,Michigan State University shooting,"East Lansing, Michigan",2/13/2023,"Anthony D. McRae, 43, opened fire at Berkey Ha...",3,5,8,School,43,Unclear,...,Black,Male,NaN,NaN,Mass,2023,East Lansing,Michigan,MI,35-64
2,Half Moon Bay spree shooting,"Half Moon Bay, California",1/23/2023,"Chunli Zhao, 67, suspected of carrying out the...",7,1,8,Workplace,67,Unclear,...,Asian,Male,NaN,NaN,Spree,2023,Half Moon Bay,California,CA,65-72
3,LA dance studio mass shooting,"Monterey Park, California",1/21/2023,"Huu Can Tran, 72,Â fled the scene in a white va...",11,10,21,Other,72,Yes,...,Asian,Male,NaN,NaN,Mass,2023,Monterey Park,California,CA,65-72
4,Virginia Walmart shooting,"Chesapeake, Virginia",11/22/2022,"Andre Bing, 31, who worked as a supervisor at ...",6,6,12,Workplace,31,Unclear,...,Black,Male,NaN,NaN,Mass,2022,Chesapeake,Virginia,VA,19-34

In [65]:
data = data.rename(columns={'case': 'Case', 'location': 'Location', 'date': 'Date','fatalities': 'Fatalities',
                            'injured': 'Injured','total_victims': 'Total victims',
                            'location.1': 'Place of incident','age_of_shooter': 'Age of shooter',
                            'prior_signs_mental_health_issues': 'Prior signs of mental health issues',
                            'race': 'Race of shooter','gender': 'Gender of shooter','type': 'Type of shooting','year': 'Year', 'age_group':'Age Group',
      })

In [66]:
data.columns

Index(['Case', 'Location', 'Date', 'summary', 'Fatalities', 'Injured',
       'Total victims', 'Place of incident', 'Age of shooter',
       'Prior signs of mental health issues', 'mental_health_details',
       'weapons_obtained_legally', 'where_obtained', 'weapon_type',
       'weapon_details', 'Race of shooter', 'Gender of shooter', 'latitude',
       'longitude', 'Type of shooting', 'Year', 'City', 'State', 'State Code',
       'Age Group'],
      dtype='object')

In [67]:
data_clean=data[['Case', 'Location', 'Date',  'Year', 'Fatalities', 'Injured',
       'Total victims', 'Type of shooting','Place of incident', 'Age of shooter', 'Age Group',  'Race of shooter', 'Gender of shooter',
       'Prior signs of mental health issues','City', 'State','State Code','latitude', 'longitude'
       ]]

In [68]:
data_clean.columns

Index(['Case', 'Location', 'Date', 'Year', 'Fatalities', 'Injured',
       'Total victims', 'Type of shooting', 'Place of incident',
       'Age of shooter', 'Age Group', 'Race of shooter', 'Gender of shooter',
       'Prior signs of mental health issues', 'City', 'State', 'State Code',
       'latitude', 'longitude'],
      dtype='object')

In [69]:
data_clean.head()

,Case,Location,Date,Year,Fatalities,Injured,Total victims,Type of shooting,Place of incident,Age of shooter,Age Group,Race of shooter,Gender of shooter,Prior signs of mental health issues,City,State,State Code,latitude,longitude
0,Nashville religious school shooting,"Nashville,Tennessee",3/27/2023,2023,6,1,6,Mass,School,28,19-34,Unclear,"F (identified as transgender, per police)",Unclear,Nashville,Tennessee,TN,NaN,NaN
1,Michigan State University shooting,"East Lansing, Michigan",2/13/2023,2023,3,5,8,Mass,School,43,35-64,Black,Male,Unclear,East Lansing,Michigan,MI,NaN,NaN
2,Half Moon Bay spree shooting,"Half Moon Bay, California",1/23/2023,2023,7,1,8,Spree,Workplace,67,65-72,Asian,Male,Unclear,Half Moon Bay,California,CA,NaN,NaN
3,LA dance studio mass shooting,"Monterey Park, California",1/21/2023,2023,11,10,21,Mass,Other,72,65-72,Asian,Male,Yes,Monterey Park,California,CA,NaN,NaN
4,Virginia Walmart shooting,"Chesapeake, Virginia",11/22/2022,2022,6,6,12,Mass,Workplace,31,19-34,Black,Male,Unclear,Chesapeake,Virginia,VA,NaN,NaN

In [70]:
data_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 19 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Case                                 141 non-null    object
 1   Location                             141 non-null    object
 2   Date                                 141 non-null    object
 3   Year                                 141 non-null    int64
 4   Fatalities                           141 non-null    int64
 5   Injured                              141 non-null    int64
 6   Total victims                        141 non-null    int64
 7   Type of shooting                     141 non-null    object
 8   Place of incident                    141 non-null    object
 9   Age of shooter                       141 non-null    object
 10  Age Group                            138 non-null    category
 11  Race of shooter                      141 non-null    object
 12  Gender of shooter                    141 non-null    object
 13  Prior signs of mental health issues  141 non-null    object
 14  City                                 141 non-null    object
 15  State                                141 non-null    object
 16  State Code                           141 non-null    object
 17  latitude                             126 non-null    float64
 18  longitude                            126 non-null    float64
dtypes: category(1), float64(2), int64(4), object(12)
memory usage: 20.3+ KB

In [71]:
data_df= data_clean[['Injured', 'Total victims']].astype(int)

In [72]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Injured        141 non-null    int32
 1   Total victims  141 non-null    int32
dtypes: int32(2)
memory usage: 1.2 KB

In [73]:
data_clean.head()

,Case,Location,Date,Year,Fatalities,Injured,Total victims,Type of shooting,Place of incident,Age of shooter,Age Group,Race of shooter,Gender of shooter,Prior signs of mental health issues,City,State,State Code,latitude,longitude
0,Nashville religious school shooting,"Nashville,Tennessee",3/27/2023,2023,6,1,6,Mass,School,28,19-34,Unclear,"F (identified as transgender, per police)",Unclear,Nashville,Tennessee,TN,NaN,NaN
1,Michigan State University shooting,"East Lansing, Michigan",2/13/2023,2023,3,5,8,Mass,School,43,35-64,Black,Male,Unclear,East Lansing,Michigan,MI,NaN,NaN
2,Half Moon Bay spree shooting,"Half Moon Bay, California",1/23/2023,2023,7,1,8,Spree,Workplace,67,65-72,Asian,Male,Unclear,Half Moon Bay,California,CA,NaN,NaN
3,LA dance studio mass shooting,"Monterey Park, California",1/21/2023,2023,11,10,21,Mass,Other,72,65-72,Asian,Male,Yes,Monterey Park,California,CA,NaN,NaN
4,Virginia Walmart shooting,"Chesapeake, Virginia",11/22/2022,2022,6,6,12,Mass,Workplace,31,19-34,Black,Male,Unclear,Chesapeake,Virginia,VA,NaN,NaN

In [74]:
data_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 19 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Case                                 141 non-null    object
 1   Location                             141 non-null    object
 2   Date                                 141 non-null    object
 3   Year                                 141 non-null    int64
 4   Fatalities                           141 non-null    int64
 5   Injured                              141 non-null    int64
 6   Total victims                        141 non-null    int64
 7   Type of shooting                     141 non-null    object
 8   Place of incident                    141 non-null    object
 9   Age of shooter                       141 non-null    object
 10  Age Group                            138 non-null    category
 11  Race of shooter                      141 non-null    object
 12  Gender of shooter                    141 non-null    object
 13  Prior signs of mental health issues  141 non-null    object
 14  City                                 141 non-null    object
 15  State                                141 non-null    object
 16  State Code                           141 non-null    object
 17  latitude                             126 non-null    float64
 18  longitude                            126 non-null    float64
dtypes: category(1), float64(2), int64(4), object(12)
memory usage: 20.3+ KB

In [75]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('us_shooting.db')
data_clean.to_sql('GunViolence', conn, if_exists='replace', index=False)

In [76]:
conn = sqlite3.connect('us_shooting.db')
df = pd.read_sql('SELECT * FROM GunViolence', conn)

In [80]:
df.head()

,Case,Location,Date,Year,Fatalities,Injured,Total victims,Type of shooting,Place of incident,Age of shooter,Age Group,Race of shooter,Gender of shooter,Prior signs of mental health issues,City,State,State Code,latitude,longitude
0,Nashville religious school shooting,"Nashville,Tennessee",3/27/2023,2023,6,1,6,Mass,School,28,19-34,Unclear,"F (identified as transgender, per police)",Unclear,Nashville,Tennessee,TN,NaN,NaN
1,Michigan State University shooting,"East Lansing, Michigan",2/13/2023,2023,3,5,8,Mass,School,43,35-64,Black,Male,Unclear,East Lansing,Michigan,MI,NaN,NaN
2,Half Moon Bay spree shooting,"Half Moon Bay, California",1/23/2023,2023,7,1,8,Spree,Workplace,67,65-72,Asian,Male,Unclear,Half Moon Bay,California,CA,NaN,NaN
3,LA dance studio mass shooting,"Monterey Park, California",1/21/2023,2023,11,10,21,Mass,Other,72,65-72,Asian,Male,Yes,Monterey Park,California,CA,NaN,NaN
4,Virginia Walmart shooting,"Chesapeake, Virginia",11/22/2022,2022,6,6,12,Mass,Workplace,31,19-34,Black,Male,Unclear,Chesapeake,Virginia,VA,NaN,NaN

In [87]:
# Export the DataFrame as a CSV file. 
#df.to_csv("CleanData/ShootingCases.csv", encoding='utf8', index=False)

#### Data for map, remove the rows with null latitude and longitude

In [78]:
data_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 19 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Case                                 141 non-null    object
 1   Location                             141 non-null    object
 2   Date                                 141 non-null    object
 3   Year                                 141 non-null    int64
 4   Fatalities                           141 non-null    int64
 5   Injured                              141 non-null    int64
 6   Total victims                        141 non-null    int64
 7   Type of shooting                     141 non-null    object
 8   Place of incident                    141 non-null    object
 9   Age of shooter                       141 non-null    object
 10  Age Group                            138 non-null    category
 11  Race of shooter                      141 non-null    object
 12  Gender of shooter                    141 non-null    object
 13  Prior signs of mental health issues  141 non-null    object
 14  City                                 141 non-null    object
 15  State                                141 non-null    object
 16  State Code                           141 non-null    object
 17  latitude                             126 non-null    float64
 18  longitude                            126 non-null    float64
dtypes: category(1), float64(2), int64(4), object(12)
memory usage: 20.3+ KB

In [81]:
map_data = data_clean.dropna(subset=['latitude'])
map_data.head()

,Case,Location,Date,Year,Fatalities,Injured,Total victims,Type of shooting,Place of incident,Age of shooter,Age Group,Race of shooter,Gender of shooter,Prior signs of mental health issues,City,State,State Code,latitude,longitude
15,Sacramento County church shooting,"Sacramento, California",2/28/2022,2022,4,0,4,Mass,Religious,0,NaN,Unclear,Male,Unclear,Sacramento,California,CA,38.601110,-121.418966
16,Oxford High School shooting,"Oxford, Michigan",11/30/2021,2021,4,7,11,Mass,School,15,10-18,Unclear,Male,Unclear,Oxford,Michigan,MI,42.844108,-83.259928
17,San Jose VTA shooting,"San Jose, California",5/26/2021,2021,9,0,9,Mass,Workplace,57,35-64,Unclear,Male,Yes,San Jose,California,CA,37.316097,-121.888533
18,FedEx warehouse shooting,"Indianapolis, Indiana",4/15/2021,2021,8,7,15,Mass,Workplace,19,10-18,White,Male,Yes,Indianapolis,Indiana,IN,39.686630,-86.323130
19,Orange office complex shooting,"Orange, California",3/31/2021,2021,4,1,5,Mass,Workplace,44,35-64,Unclear,Male,Unclear,Orange,California,CA,33.835420,-117.853790

In [82]:
map_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 126 entries, 15 to 140
Data columns (total 19 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Case                                 126 non-null    object
 1   Location                             126 non-null    object
 2   Date                                 126 non-null    object
 3   Year                                 126 non-null    int64
 4   Fatalities                           126 non-null    int64
 5   Injured                              126 non-null    int64
 6   Total victims                        126 non-null    int64
 7   Type of shooting                     126 non-null    object
 8   Place of incident                    126 non-null    object
 9   Age of shooter                       126 non-null    object
 10  Age Group                            123 non-null    category
 11  Race of shooter                      126 non-null    object
 12  Gender of shooter                    126 non-null    object
 13  Prior signs of mental health issues  126 non-null    object
 14  City                                 126 non-null    object
 15  State                                126 non-null    object
 16  State Code                           126 non-null    object
 17  latitude                             126 non-null    float64
 18  longitude                            126 non-null    float64
dtypes: category(1), float64(2), int64(4), object(12)
memory usage: 19.0+ KB

In [84]:
conn = sqlite3.connect('us_shooting.db')
map_data.to_sql('MapTable', conn, if_exists='replace', index=False)

In [85]:
conn = sqlite3.connect('us_shooting.db')
df_map = pd.read_sql('SELECT * FROM MapTable', conn)

In [86]:
df_map.head()

,Case,Location,Date,Year,Fatalities,Injured,Total victims,Type of shooting,Place of incident,Age of shooter,Age Group,Race of shooter,Gender of shooter,Prior signs of mental health issues,City,State,State Code,latitude,longitude
0,Sacramento County church shooting,"Sacramento, California",2/28/2022,2022,4,0,4,Mass,Religious,0,None,Unclear,Male,Unclear,Sacramento,California,CA,38.601110,-121.418966
1,Oxford High School shooting,"Oxford, Michigan",11/30/2021,2021,4,7,11,Mass,School,15,10-18,Unclear,Male,Unclear,Oxford,Michigan,MI,42.844108,-83.259928
2,San Jose VTA shooting,"San Jose, California",5/26/2021,2021,9,0,9,Mass,Workplace,57,35-64,Unclear,Male,Yes,San Jose,California,CA,37.316097,-121.888533
3,FedEx warehouse shooting,"Indianapolis, Indiana",4/15/2021,2021,8,7,15,Mass,Workplace,19,10-18,White,Male,Yes,Indianapolis,Indiana,IN,39.686630,-86.323130
4,Orange office complex shooting,"Orange, California",3/31/2021,2021,4,1,5,Mass,Workplace,44,35-64,Unclear,Male,Unclear,Orange,California,CA,33.835420,-117.853790